providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

api:
  insecure: true

pilot:
  token: "$TRAEFIK_PILOT_TOKEN"

experimental:
  devPlugin:
    goPath: /plugins/go
    moduleName: github.com/rsteube/traefik-plugin-brotli
